### PR TITLE
More updates

### PR DESCRIPTION
**Pull request by Iridium-IO**
* Updated more translations for English
* Adjusted layout to be consistent between English and Chinese versions
* Redesigned the Settings page and "Add Item" Form to fix visual bugs
* Added a separate English Readme file with links to go back and forth
* Restructured the Readme to be clearer

### CODE REVIEW

**Comment by flier268** [comment]
This is traditional chinese,not simplified chinese
So,the image is wrong

**Comment by flier268** [comment]
1.DataGetter\Form1.en.resx not found

2.
image
Some Text can not view

**Comment by ImminentFate** [comment]
Ah i might have broken some stuff in the push to GitHub :/ I'll fix it and get back to you

**Comment by Iridium-IO** [comment]
Alright, I've fixed the text here: 
image

Not sure about the "DataGetter\Form1.en.resx not found" because that file shouldn't exist anyway :/

Which image is wrong by the way? Sorry for getting it wrong.
Is it the Readme one? Should it be this?
image

**Comment by flier268** [comment]
Yes,it is

**Comment by Iridium-IO** [comment]
Alright should be all fixed now :)

**Pull request merged**
